config : {
  paths: [
    home_dir: '',
    data_dir: '/binance data',
    balances_dir: '/binance data/balances'],
  modules: [
    download_balances: yes,
    download_daily_account_snapshots: yes,
    download_trades: yes,
    download_orders: yes,
    download_open_orders: yes,
    download_deposits: yes,
    download_withdrawals: yes,
    balance_ticker: yes,
    download_prices: yes],
  accounts: [
    Account1: [
      dir: dir1,
      type: SPOT,
      osvar_api_public: READ_PUBLIC_A1_SPOT,
      osvar_api_secret: READ_SECRET_A1_SPOT,
      chat_pseudo: A1,
      chat_id: '@A1',
      investment: 1000,
      cash: 0,
      portval: 0,
      profit: 0],
    Account2: [
      dir: dir2,
      type: FUTURES,
      osvar_api_public: READ_PUBLIC_A2_FUTURES,
      osvar_api_secret: READ_SECRET_A2_FUTURES,
      chat_pseudo: A2,
      chat_id: '@S2',
      investment: 2000,
      cash: 0,
      portval: 0,
      profit: 0]],
  account_groups: [
    ALL: [
      accounts: [A1, A2],
      chat_id: '@A3',
      chat_pseudo: all]],
  telegram: [
    token: <telegram-token>],    
  logging: [
    log_activate: yes,
    log_level: INFO,
    log_target: console,
    log_file : binance_reporting.log],
  download_klines: [
    trading_pairs: 'USDT',
    kline_interval: ['5m', '1d']],
  download_daily_account_snapshots: [
    snapshot_days_max: 180,
    snapshot_days_per_request: 30]
  }
